### ISSUE TITLE
StringFormat category too global?

### ISSUE THREAD

**Issue by stijnvanhoey** [LifeWatchINBO/dwca-validator#2]
In the current  settings-file which makes the translation of the guidelines to [yaml-settings](https://github.com/LifeWatchINBO/dwca-validator/blob/structure/settings.yaml) file for the different terms, following categories are derived:
- Equal
- NotEqual
- Conditional
- ValidDataType (json, integer...)
- Delimiter
- StringFormat (ISO8601, UpperCamelCase, lowercase, .5f)

However, maybe we should split the StringFormat category further into: CaseFormat, FloatFormat, DateFormat,... Would this result in overkill, or rather more clearness in the definitions? 
@peterdesmet ?

**Comment by peterdesmet** [comment]
It's indeed a bit weird to define `ISO8601` or `.5f` as a StringFormat, even though it could be implemented as such at first. I think it would be more clear to indeed split in the formats you suggest.

**Comment by peterdesmet** [comment]
Maybe it would also make more sense to have `Conditional` as an argument for any of the other tests. E.g.

```
geodeticDatum :
  - Equal : WGS84, decimalLatitude
```

**Comment by stijnvanhoey** [comment]
Due to the #5 restructering and reframing of the tests syntax in yaml file, this discussion/issue is no longer up to date, so closing
